---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  environments_path: test/environments
  data_bags_path: test/fixtures/data_bags
  encrypted_data_bag_secret_key_path: test/fixtures/encrypted_data_bag_secret

verifier:
  name: inspec

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init

- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-5
  driver:
    image: dokken/centos-5
    pid_one_command: /sbin/init

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-26
  driver:
    image: dokken/fedora-26
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-27
  driver:
    image: dokken/fedora-27
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-12.04
  driver:
    image: dokken/ubuntu-12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-17.04
  driver:
    image: dokken/ubuntu-17.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-17.10
  driver:
    image: dokken/ubuntu-17.10
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd

suites:
- name: testing
  provisioner:
    client_rb:
      environment: testing
  run_list:
  - recipe[test::default]

- name: staging
  provisioner:
    client_rb:
      environment: staging
  run_list:
  - recipe[test::default]
